services:
  py:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - config-volume:/root/.jupyter
      - ${PWD}:/workspace

volumes:
  config-volume:
